# Generated by Django 4.0.2 on 2022-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
